/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Sat, Oct 22, 2016                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :RX63N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
/************************************************************************
*
* Device     : RX/RX600/RX63N
*
* File Name  : hwsetup.c
*
* Abstract   : Hardware Setup file.
*
* History    : 0.10  (2011-02-21)  [Hardware Manual Revision : 0.01]
*
* NOTE       : THIS IS A TYPICAL EXAMPLE.
*
* Copyright (C) 2011 Renesas Electronics Corporation.
* and Renesas Solutions Corp.
*
************************************************************************/

#include "iodefine.h"
#include "hwsetup_rx631.h"
#include "clock.h"
#include "port.h"
#include "tpu.h"
#include "sci.h"
#include "dac.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif

void HardwareSetup(void)
{
    //--------------------------------------------------------------------------------
    // Stop/Run modules
    //--------------------------------------------------------------------------------
    // TBD

    //================================================================================
    // Initialize modules
    //================================================================================
    PORT_init();        // Should be done first, before multiplexed pin setting.

    CLOCK_init();

    TPU_init();
    TPU_restart_ch(0);

    SCI_init();

    DAC_init();

    // TBD: ADC_init();

    //================================================================================
    // Interrupt Controller setting
    //================================================================================
    IPR(TPU0,   TGI0A)      = 2;    // Interrupt PRiority level
                                    //  0:      prohibit interrupt
                                    //  1--15:  larger --> higher priority
    // TBD: IPR(S12AD0,  S12ADI0)    = 3;
    //--------------------------------------------------------------------------------
    IEN(TPU0,   TGI0A)      = 1;    // Interrupt ENable
                                    //  0: disable, 1: enable
    // TBD: IEN(S12AD0,  S12ADI0)    = 1;    // Enable S12AD interrupt
}
