/***********************************************************************/
/*                                                                     */
/*  FILE        :lowsrc.h                                              */
/*  DATE        :Sat, Oct 22, 2016                                     */
/*  DESCRIPTION :Header file of I/O Stream file                        */
/*  CPU TYPE    :RX63N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
/*Number of I/O Stream*/
#define IOSTREAM 20
