/***********************************************************************/
/*                                                                     */
/*  FILE        :rx631_sample.c                                        */
/*  DATE        :Sat, Oct 22, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX63N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

//----------------------------------------
// GR-CITRUS, Akizuki RX631 CPU board
// CPU chip: R5F5631FDDFP 100pin LQFP
// ROM 2MB      FFE0_0000hÅ`FFFF_FFFFh
// RAM 256kB    0000_0000hÅ`0003_FFFFh
//----------------------------------------

//----------------------------------------
// Akizuki RX621 CPU board
// CPU chip: RF56218BDEP
// ROM 512KB    FFF8_0000hÅ`FFFF_FFFFh
// RAM 96KB     0000_0000hÅ`0001_7FFFh
//----------------------------------------

//----------------------------------------
// Akizuki RX220 CPU board
// CPU chip: RF52206BDFM
// ROM 256KB    FFFC_0000hÅ`FFFF_FFFFh
// RAM 16KB     0000_0000hÅ`0000_3FFFh
//----------------------------------------

#include "iodefine.h"

#include "util.h"           // tcnt_show(), ms_abs_count_show()
#include "port.h"
#include "tpu.h"
#include "sci.h"
#include "etc.h"
#include "stack_var_adrs.h"

#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

//------------------------------------------------------------
// Global variables
//------------------------------------------------------------
int     g_ms_abs_count  = 0;
int     g_ms_count      = 0;    // g_ms_count={0, 1, ..., 999}
int     g_led1          = 0;    // 0 or 1
int     g_dac1_u10      = 0;    // DAC1, 10bit

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
    SCIprintf("    \n");
    SCIprintf("\n");

    SCIprintf("-----------------------------------\n");
    SCIprintf("GR-CITRUS, Akizuki RX631, 2016\n");
    SCIprintf("-----------------------------------\n");
    SCIprintf("sizeof(double)=%d\n", sizeof(double));
    SCIprintf("\n");
    SCIprintf("Hello, world.\n");

    //--------------------------------------------------------------------------------
    // Main loop
    //--------------------------------------------------------------------------------
	while(1) {
        g_led1 = (g_ms_count>800) ? 1 : 0;  // g_ms_count is updated in the intprg.c/Excep_TPU0_TGIA0()
                                            // interrupt function every 1ms.
    }
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
