/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Sat, Oct 22, 2016                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :RX63N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x400
